### ISSUE TITLE
[FEATURE] TrackingHive API Support

### ISSUE THREAD

**Issue by maxirus** [jat255/PackageMate#20]
Feature request to add the ability to use the [TrackingHive](https://my.trackinghive.com/) API service to pull data from many carriers in a single place. TrackingHive requires no PII, Credit Card, etc. to sign-up and is extremely simple. This would alleviate the need to implement unsupported carriers as most already supported by TrackingHive.

**Comment by jat255** [comment]
Sorry for the delay getting back around to this.

TrackingHive looks pretty cool from a tech perspective, but I don't really have an interest in integrating their API, since it sort of goes against the idea of a self-hosted solution and control of your data (i.e. some random third party will have in their database a record of every package I track associated with whatever email address I give them via my API key). 

That being said, I'm not totally against including that functionality if someone wants to code it; it's just not something I'm going to spend time on.
